version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ${SPRING_REDIS_HOST}
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-user/Dockerfile
    container_name: user_service
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  video-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-video/Dockerfile
    container_name: video_service
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  adjust-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-adjust/Dockerfile
    container_name: adjust_service
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
