version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # 호스트의 3307 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"  # 호스트의 6380 포트를 컨테이너의 6379 포트에 매핑

  eureka-server:
    build:
      context: ./  # Root context for the build
      dockerfile: module-eureka/Dockerfile
    container_name: eureka_server
    env_file:
      - .env
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - redis

  user-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-user/Dockerfile
    container_name: user_service
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  video-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-video/Dockerfile
    container_name: video_service
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - /var/www/uploads/adjustment:/var/www/uploads/adjustment

  adjust-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-adjust/Dockerfile
    container_name: adjust_service
    ports:
      - "8084:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  batch-service:
    build:
      context: ./  # Root context for the build
      dockerfile: module-batch/Dockerfile
    container_name: batch_service
    ports:
      - "8085:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  gateway:
    build:
      context: ./  # Root context for the build
      dockerfile: module-gateway/Dockerfile
    container_name: gateway
    ports:
      - "8086:8080"  # Gateway 서비스는 기본적으로 8080 포트 사용
    env_file:
      - .env
    depends_on:
      - eureka-server  # Eureka에 의존
      - user-service
      - video-service
      - adjust-service
volumes:
  mysql_data:
