name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 변경 감지를 위한 이전 파일 확인

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SSH with file deletion
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/leesh/Sparta/AdjustmentService

      - name: Install Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 'bash -s' << 'EOF'
          curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          EOF

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /home/leesh/Sparta/AdjustmentService
          
          # 환경 변수 저장
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          
          # Detect which modules changed
          changed_modules=$(git diff --name-only HEAD^ HEAD)

          # Build all services if module-common changed
          if echo "$changed_modules" | grep -q '^module-common/'; then
            echo "Changes detected in common module"
            docker-compose build user-service
            docker-compose build video-service
            docker-compose build adjust-service
            docker-compose build batch-service
            docker-compose build eureka-server
            docker-compose build gateway
            docker-compose build common
          else
            # Build only if specific directories have changed
            if echo "$changed_modules" | grep -q '^module-user/'; then
              echo "Changes detected in user-service"
              docker-compose build user-service
            fi

            if echo "$changed_modules" | grep -q '^module-video/'; then
              echo "Changes detected in video-service"
              docker-compose build video-service
            fi

            if echo "$changed_modules" | grep -q '^module-adjust/'; then
              echo "Changes detected in adjust-service"
              docker-compose build adjust-service
            fi
          
            if echo "$changed_modules" | grep -q '^module-batch/'; then
              echo "Changes detected in batch-service"
              docker-compose build batch-service
            fi
          
            if echo "$changed_modules" | grep -q '^module-eureka/'; then
              echo "Changes detected in eureka-service"
              docker-compose build eureka-server
            fi
          
            if echo "$changed_modules" | grep -q '^module-gateway/'; then
              echo "Changes detected in gateway"
              docker-compose build gateway
            fi
          fi
          
          docker-compose up -d
          EOF